"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { PayrollForm } from "./payroll-form";
import { PayrollManagementForm } from "./management-form";
import { withAuth } from "@/components/withAuth";

function PayrollPage() {
  return (
    <div className="grid gap-3 md:gap-4">
      <Tabs defaultValue="payroll">
        <TabsList className="mb-4">
          <TabsTrigger value="payroll">Payroll</TabsTrigger>
          <TabsTrigger value="management">Payroll Management</TabsTrigger>
        </TabsList>

        <TabsContent value="payroll">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg md:text-xl">
                Generate Payroll Report
              </CardTitle>
              <CardDescription className="text-sm">
                Select a date range to generate a payroll report. The report will
                be generated by an AI assistant and will include all calculations
                and adjustments required by Washington state labor laws.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <PayrollForm />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="management">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg md:text-xl">
                Payroll Management
              </CardTitle>
              <CardDescription className="text-sm">
                Select a date range and one or more clients to generate a
                consolidated summary of all pieces worked, grouped by date, task
                and variety, with total quantities and amounts.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <PayrollManagementForm />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

export default withAuth(PayrollPage, { askEveryVisit: true });
