
'use client'

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { PayrollForm } from "./payroll-form"
import { withAuth } from '@/components/withAuth'


function PayrollPage() {
  return (
    <div className="grid gap-3 md:gap-4">
      <Card>
        <CardHeader>
          <CardTitle className="text-lg md:text-xl">Generate Payroll Report</CardTitle>
          <CardDescription className="text-sm">
            Select a date range to generate a payroll report. The report will be generated by an AI assistant and will include all calculations and adjustments required by Washington state labor laws.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <PayrollForm />
        </CardContent>
      </Card>
    </div>
  )
}

export default withAuth(PayrollPage);
