// This file is automatically generated. Do not modify it manually.

// Follow the instructions in the Firebase console to configure your app.
// The Firebase console provides a code snippet with your web app's
// configuration object. You should replace the empty object below
// with the configuration object from the Firebase console.
//
// https://firebase.google.com/docs/web/setup#config-object

export const firebaseConfig = {};
